version: '3.8'

services:
  auth-db:
    image: postgres:16-alpine 
    container_name: clinic-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: InnowiseSuperSecretPassword123!
      POSTGRES_DB: AuthDB
    ports:
      - "5432:5432" 
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  auth-redis:
    image: redis:7-alpine
    container_name: clinic-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - auth-redis-data:/data
    networks:
      - clinic-network

  offices-db:
    image: mongo:7.0
    container_name: clinic-offices-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: InnowiseMongoSecretPassword123!
    ports:
      - "27017:27017"
    volumes:
      - offices-db-data:/data/db
    networks:
      - clinic-network

  profiles-db:
    image: postgres:16-alpine
    container_name: clinic-profiles-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: InnowiseSuperSecretPassword123!
      POSTGRES_DB: ProfilesDB
    ports:
      - "5433:5432" # Локальный внешний порт 5433
    volumes:
      - profiles-db-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: clinic-rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
    - clinic-network

  appointments-db:
    image: postgres:16-alpine
    container_name: clinic-appointments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: InnowiseSuperSecretPassword123!
      POSTGRES_DB: AppointmentsDB
    ports:
      - "5434:5432" # Локальный внешний порт 5434
    volumes:
      - appointments-db-data:/var/lib/postgresql/data
    networks:
      - clinic-network


networks:
  clinic-network:
    driver: bridge

volumes:
  auth-db-data:
  appointments-db-data:
  auth-redis-data:
  offices-db-data:
  profiles-db-data:
  rabbitmq_data: